### PR TITLE
added allPass and anyPass

### PR DESCRIPTION
**Pull request by ni-ko-o-kin**
inspired by ramdas http://ramdajs.com/docs/#allPass and http://ramdajs.com/docs/#anyPass

### CODE REVIEW

**Comment by Chadtech** [comment]
Hey @ni-ko-o-kin 

I appreciate the PR and I can see the utility in these functions. However, I dont think it really pertains to `list-extra`. These functions arent useful for working with lists generally, rather they have some specific application that just _happens_ to use lists.

Its funny you bring this up now tho. I was just thinking about making a `Bool-Extra`, since I often use functions like `allTrue : List Bool -> Bool`. It seems like there should be some package out there that would include functions like `anyPass` and `allTrue`. Would you mind if I made that package? Or, I could make the package and you could submit a PR just like this one?

**Comment by ni-ko-o-kin** [comment]
Sure! Let me know when the repository is ready!

**Comment by Chadtech** [comment]
Awesome. I just set up this repo here: https://github.com/Chadtech/elm-bool-extra . If you make a PR on it, I'll publish the package.

**Comment by ni-ko-o-kin** [comment]
done

**Comment by Chadtech** [comment]
And published. I incorporated your changes and got them out as release 1.1.0

**Pull request closed without merging**
